.TH "HTTPRequest" 3 "Wed Sep 14 2022" "web-server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTPRequest
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBmethod\fP"
.br
.ti -1c
.RI "char * \fBuri\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "\fBHTTPHeaders\fP * \fBheaders\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct represents a typical HTTP Request parsed from a web client 
.PP
Definition at line \fB15\fP of file \fBhttp\-handler\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "\fBHTTPHeaders\fP* HTTPRequest::headers"
The additional headers requested from the web client 
.PP
Definition at line \fB23\fP of file \fBhttp\-handler\&.c\fP\&.
.PP
Referenced by \fBhandleHTTPClientRequest()\fP\&.
.SS "char* HTTPRequest::method"
The requested HTTP method 
.PP
Definition at line \fB17\fP of file \fBhttp\-handler\&.c\fP\&.
.PP
Referenced by \fBhandleHTTPClientRequest()\fP\&.
.SS "char* HTTPRequest::uri"
The requested HTTP URI 
.PP
Definition at line \fB19\fP of file \fBhttp\-handler\&.c\fP\&.
.PP
Referenced by \fBhandleHTTPClientRequest()\fP\&.
.SS "char* HTTPRequest::version"
The version of the HTTP from the web client 
.PP
Definition at line \fB21\fP of file \fBhttp\-handler\&.c\fP\&.
.PP
Referenced by \fBhandleHTTPClientRequest()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for web-server from the source code\&.
