/home/clover/Projects/web-server/lib/stack.h
NAME
/home/clover/Projects/web-server/lib/stack.h
SYNOPSIS
#include 'http-header.h'
Data Structures
struct StackNode
Typedefs
typedef struct StackNode * Stack
typedef struct StackNode * NextStackNode
Functions
Stack stackInit (void)
void stackFree (Stack stack, void(freeMethod)(Element))
void stackPush (Element element, Stack stack)
void stackPop (Stack stack, void(freeMethod)(Element))
Detailed Description
Author
Little Clover
Date
2022-09-14 14:11:46 PM +0800
Definition in file stack.h.
Typedef Documentation
typedef struct StackNode* NextStackNode
Define the next pointed stack node as a StackNode
Definition at line 17 of file stack.h.
typedef struct StackNode* Stack
Define stack as a pointer to a StackNode
Definition at line 13 of file stack.h.
Function Documentation
void stackFree (Stack stack, void(freeMethod)(Element))
Free a stack
Parameters
stack A stack to be freed
Definition at line 33 of file stack.c.
                                                        {
  do {
    stackPop(stack, freeMethod);
  } while (stack->next);
}
References StackNode::next, and stackPop().
Referenced by httpRequestFree().
Stack stackInit (void)
Initialise an empty stack
Returns
An empty stack
Definition at line 7 of file stack.c.
                      {
  Stack newStack = malloc(sizeof(struct StackNode));
  if (!newStack) {
    errno = ENOMEM;
    perror("stack");
    exit(EXIT_FAILURE);
  }
  newStack->next = NULL;
  return newStack;
}
References StackNode::next.
Referenced by httpRequestInit().
void stackPop (Stack stack, void(freeMethod)(Element))
Pop the top element to a stack
Parameters
stack A stack
Definition at line 20 of file stack.c.
                                                       {
  NextStackNode top;
  if (stack->next) {
    top = stack->next;
    stack->next = stack->next->next;
    freeMethod(top->element);
    free(top);
  } else {
    fprintf(stderr, "stack: empty stack\n");
  }
}
References StackNode::element, and StackNode::next.
Referenced by stackFree().
void stackPush (Element element, Stack stack)
Push an element to the top a stack
Parameters
element Element to be pushed
stack A stack
Definition at line 39 of file stack.c.
                                             {
  NextStackNode tmp;
  tmp = malloc(sizeof(struct StackNode));
  if (!tmp) {
    errno = ENOMEM;
    perror("stack");
    exit(EXIT_FAILURE);
  }
  tmp->element = element;
  tmp->next = stack->next;
  stack->next = tmp;
}
References StackNode::element, and StackNode::next.
Author
Generated automatically by Doxygen for web-server from the source code.